<?xml version="1.0" encoding="utf-8"?>
<TestRun id="b8fec423-bb9f-49f0-95e6-d2c67aa318da" name="mujee@LAPTOP-D8KES1NV 2023-01-28 13:12:00" runUser="LAPTOP-D8KES1NV\mujee" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-28T13:12:00.6058795+05:00" queuing="2023-01-28T13:12:00.6058795+05:00" start="2023-01-28T13:11:56.4333586+05:00" finish="2023-01-28T13:12:04.6637637+05:00" />
  <TestSettings name="default" id="296dc48a-3ac7-4e8e-9f7d-f6271315931d">
    <Deployment runDeploymentRoot="mujee_LAPTOP-D8KES1NV_2023-01-28_13_12_00" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="56bfce24-d385-465d-8970-69566122d714" testId="51c907ea-d784-4a4f-a024-c6e49a2633ad" testName="CheckOutTC_001" computerName="LAPTOP-D8KES1NV" duration="00:00:01.9488922" startTime="2023-01-28T13:12:02.4743628+05:00" endTime="2023-01-28T13:12:04.4234043+05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="56bfce24-d385-465d-8970-69566122d714">
      <Output>
        <ErrorInfo>
          <Message>Test method FinalExam.TestExecution.CheckOutTC_001 threw exception: &#xD;
System.NullReferenceException: Object reference not set to an instance of an object.</Message>
          <StackTrace>    at FinalExam.LoginPage.Login1(String user, String pass) in C:\Users\mujee\source\repos\FinalExam\FinalExam\SauceDemo\LoginPage\LoginPage.cs:line 15&#xD;
   at FinalExam.TestExecution.CheckOutTC_001() in C:\Users\mujee\source\repos\FinalExam\FinalExam\SauceDemo\TestExecution.cs:line 43&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="52f32aeb-16ec-4a78-b45f-98a22a7ea18c" testId="73ed0b71-f38d-4ea2-86a3-caf94b25e7b9" testName="LoginTC_001" computerName="LAPTOP-D8KES1NV" duration="00:00:03.2438688" startTime="2023-01-28T13:11:57.2211778+05:00" endTime="2023-01-28T13:12:00.5410552+05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="52f32aeb-16ec-4a78-b45f-98a22a7ea18c">
      <Output>
        <ErrorInfo>
          <Message>Test method FinalExam.TestExecution.LoginTC_001 threw exception: &#xD;
System.NullReferenceException: Object reference not set to an instance of an object.</Message>
          <StackTrace>    at FinalExam.LoginPage.Login1(String user, String pass) in C:\Users\mujee\source\repos\FinalExam\FinalExam\SauceDemo\LoginPage\LoginPage.cs:line 15&#xD;
   at FinalExam.TestExecution.LoginTC_001() in C:\Users\mujee\source\repos\FinalExam\FinalExam\SauceDemo\TestExecution.cs:line 22&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="c229bbb4-3dbf-4263-af4d-0b051a4bba27" testId="6426bd24-9087-4a56-8f01-b12d013f66b1" testName="AddProductTC_001" computerName="LAPTOP-D8KES1NV" duration="00:00:01.8925007" startTime="2023-01-28T13:12:00.5809820+05:00" endTime="2023-01-28T13:12:02.4743628+05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c229bbb4-3dbf-4263-af4d-0b051a4bba27">
      <Output>
        <ErrorInfo>
          <Message>Test method FinalExam.TestExecution.AddProductTC_001 threw exception: &#xD;
System.NullReferenceException: Object reference not set to an instance of an object.</Message>
          <StackTrace>    at FinalExam.LoginPage.Login1(String user, String pass) in C:\Users\mujee\source\repos\FinalExam\FinalExam\SauceDemo\LoginPage\LoginPage.cs:line 15&#xD;
   at FinalExam.TestExecution.AddProductTC_001() in C:\Users\mujee\source\repos\FinalExam\FinalExam\SauceDemo\TestExecution.cs:line 35&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="9a91c76d-f719-4558-b3ac-044ca63e1c79" testId="0207c2dc-0c92-453e-ba7b-006b44d9b72d" testName="Login1" computerName="LAPTOP-D8KES1NV" duration="00:00:00.0050786" startTime="2023-01-28T13:12:04.4244022+05:00" endTime="2023-01-28T13:12:04.4373666+05:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="9a91c76d-f719-4558-b3ac-044ca63e1c79">
      <Output>
        <ErrorInfo>
          <Message>Test method FinalExam.LoginPage.Login1 threw exception: &#xD;
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.TestFailedException: Only data driven test methods can have parameters. Did you intend to use [DataRow] or [DynamicData]?</Message>
          <StackTrace>   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)&#xD;
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="AddProductTC_001" storage="c:\users\mujee\source\repos\finalexam\finalexam\bin\debug\finalexam.dll" id="6426bd24-9087-4a56-8f01-b12d013f66b1">
      <Execution id="c229bbb4-3dbf-4263-af4d-0b051a4bba27" />
      <TestMethod codeBase="C:\Users\mujee\source\repos\FinalExam\FinalExam\bin\Debug\FinalExam.dll" adapterTypeName="executor://mstestadapter/v2" className="FinalExam.TestExecution" name="AddProductTC_001" />
    </UnitTest>
    <UnitTest name="CheckOutTC_001" storage="c:\users\mujee\source\repos\finalexam\finalexam\bin\debug\finalexam.dll" id="51c907ea-d784-4a4f-a024-c6e49a2633ad">
      <Execution id="56bfce24-d385-465d-8970-69566122d714" />
      <TestMethod codeBase="C:\Users\mujee\source\repos\FinalExam\FinalExam\bin\Debug\FinalExam.dll" adapterTypeName="executor://mstestadapter/v2" className="FinalExam.TestExecution" name="CheckOutTC_001" />
    </UnitTest>
    <UnitTest name="Login1" storage="c:\users\mujee\source\repos\finalexam\finalexam\bin\debug\finalexam.dll" id="0207c2dc-0c92-453e-ba7b-006b44d9b72d">
      <Execution id="9a91c76d-f719-4558-b3ac-044ca63e1c79" />
      <TestMethod codeBase="C:\Users\mujee\source\repos\FinalExam\FinalExam\bin\Debug\FinalExam.dll" adapterTypeName="executor://mstestadapter/v2" className="FinalExam.LoginPage" name="Login1" />
    </UnitTest>
    <UnitTest name="LoginTC_001" storage="c:\users\mujee\source\repos\finalexam\finalexam\bin\debug\finalexam.dll" id="73ed0b71-f38d-4ea2-86a3-caf94b25e7b9">
      <Execution id="52f32aeb-16ec-4a78-b45f-98a22a7ea18c" />
      <TestMethod codeBase="C:\Users\mujee\source\repos\FinalExam\FinalExam\bin\Debug\FinalExam.dll" adapterTypeName="executor://mstestadapter/v2" className="FinalExam.TestExecution" name="LoginTC_001" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="51c907ea-d784-4a4f-a024-c6e49a2633ad" executionId="56bfce24-d385-465d-8970-69566122d714" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="73ed0b71-f38d-4ea2-86a3-caf94b25e7b9" executionId="52f32aeb-16ec-4a78-b45f-98a22a7ea18c" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="6426bd24-9087-4a56-8f01-b12d013f66b1" executionId="c229bbb4-3dbf-4263-af4d-0b051a4bba27" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestEntry testId="0207c2dc-0c92-453e-ba7b-006b44d9b72d" executionId="9a91c76d-f719-4558-b3ac-044ca63e1c79" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="4" executed="4" passed="0" failed="4" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
</TestRun>